version: '3'
services:
  front:
    build: ./front
    depends_on:
      - back
    ports:
      - 80:80
  back:
    build: ./back
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
  apache:
    build: ./apache
    ports:
      - 8080:80
    volumes:
      - ./front/build:/var/www/html/front
      - ./back:/var/www/html/back
    depends_on:
      - front
      - back
volumes:
  db_data:
